### ISSUE TITLE
`segmentation fault (core dumped)` when using `qa->Query(runnum,evnum)`

### ISSUE THREAD

**Issue by rtysonCLAS12** [c-dilks/clasqaDB#1]
Hi,

When using the function `qa->Query(runnum,evnum)` I get a `segmentation fault (core dumped)` error. This happens at line 97 of `QADB.h`: `auto runDOM = jsonDOM[runnumStr].GetObject();`.

I see this error when running the code from `example_dumpQA.cpp`, although I run it through clas12root instead of compiling it with g++. This bug happens to me for both bogus and proper run numbers. I created my own code in rapidjson to merge the json files from `qa.inbending1`, `qa.inbending2` and `qa.outbending`, but I still see this issue when trying to run the example on each of these files individually (although I'm guessing run 5160 is contained in only one of these json files).

For context, I am using the version of rapidjson that is included in your github repository, and I am including the clasqaDB and rapidjson include directories into the clas12root build with CMake using:

    include_directories($ENV{CLASQADB_HOME}/srcC/rapidjson/include)
    include_directories($ENV{CLASQADB_HOME}/srcC/include)

Thanks for your help,
Richard

**Comment by c-dilks** [comment]
Hi Richard,
Have you tried compiling your code with g++ or gcc? Are you using Cling for interpretation, or are you compiling 'on-the-fly' with ACliC? Could you please send me a minimal example of your usage, so I can better diagnose the issue?
Thanks,
Chris

**Comment by rtysonCLAS12** [comment]
Hi Chris,

I've been trying to run example_dumpQA.cpp. Compiling with g++ works, and I can run it in clas12root with ACliC by running the macro with `.x example_dumpQA.cpp+`. However, when just using Cling with `.x example_dumpQA.cpp` this leads to the bug mentioned above.

That being said, I've changed my version of ROOT from 6.20 to 6.22 and it now works fine with Cling. I'm not entirely sure why this is the case but at least I now have your code running.

In any case thanks a lot for your help!

**Comment by c-dilks** [comment]
Interesting.. I've not had any issue using either ROOT 6.20/04 or 6.18/00, with compiled analysis code. In any case, it seems to work better when compiled, rather than interpreted with Cling. I will note this in the documentation, thanks for figuring this out.
